import { Jost } from "next/font/google";
import "./globals.css";
import "sweetalert2/src/sweetalert2.scss";

const jost = Jost({ subsets: ["latin-ext"] });
import { NextAuthProvider } from "@/provider/NextAuthProvider";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jost.className}>
        <NextAuthProvider>{children}</NextAuthProvider>
      </body>
    </html>
  );
}
